### ISSUE TITLE
Druck-Funktion oder Export nach PDF

### ISSUE THREAD

**Issue by mipastgt** [mipastgt/AIPBrowserDE-Public#2]
_(Von DIFH im ulForum)_

Tolles Programm, ich benutze es obwohl ich Zugriff auf die bezahlte "große" AIP habe.

Ein Feature wäre für eine zukünftige Version noch schön: Vielleicht bin ich etwas altmodisch, aber ich drucke mir das Anflugblatt  aus (zusätzlich zur elektronischen Form). Die meisten Fluglehrer verlangen das auch von ihren Flugschülern. Also eine Druck-Funktion oder Export nach PDF wäre schön. Möglichst mehrseitig, damit man im Duplex-Druck Vor- und Rückseite (Anflugblatt  und Rollkarte) bedrucken kann. Ich behelfe mir im Moment damit, dass ich die exportierten Bilder zu einem mehrseitiges TIFF-Dokument verbinde.

**Comment by mipastgt** [comment]
Eine direkte Druck-Funktion wird es wohl nicht geben, da es beim Drucken immer wieder zu Problemen kommt und ich das nicht unbedingt supporten will. Ein PDF-Export ist allerdings bereits in Planung. Ich überlege nur noch wie man möglichst komfortabel selektieren soll was man exportieren will. Diese Funktion steht auch im Zusammenhang mit der Trip-Kit-Erstellung.

**Comment by mipastgt** [comment]
_(Von DIFH im ulForum)_

Bei Jeppesen JeppView kann man einfach die gewünschten Blätter in dem Treeview markieren (multiselect).

**Comment by mipastgt** [comment]
Diese Funktion ist ab der Version 1.1.2 implementiert und wird über den schon vorhandenen Export-Knopf angestoßen.

_Was dabei genau exportiert wird, hängt von der Auswahl ab. Wenn man einen Flugplatzordner ausgewählt hat, dann werden alle darin enthaltenen Seiten zu einer PDF-Datei zusammengefasst und exportiert. Wenn man also z.B. den Ordner "Aachen-Merzbrueck EDKA" auswählt, dann werden die darin enthaltenen Seiten "EDKA Aachen-Merzbrueck 1", "EDKA Aachen-Merzbrueck 2" und "AD 2-3" als eine PDF-Datei abgespeichert._

**Comment by Michael-Wellner** [comment]
Vielen Dank für diese Funktion, die zwar nicht gleich intuitiv gefunden wurde, sich aber nunmehr als ungeheuer nützlich erweist.
Vielleicht gibt es aber dennoch eine Möglichkeit, ggf. auch über die Einstellungen das "bevorzugte" Exportformat zu wählen.
Weiterhin wäre es praktisch, wenn man eben auch mehrere Karten direkt auswählen könnte. Mit gelingt es derzeit zumindest nur immer eine Karte mit einem "Häkchen" zu versehen.

**Comment by mipastgt** [comment]
Das ist für die nächste Version bereits implementiert und eine Ergänzung des Trip-Kits.
```
{
    "version": "1.0.0",
    "name": "Hahnweide to Aachen",
    "description": "A trip from Hahnweide to Aachen via Speyer and Koblenz",
    "pages": {
        "pageFormat": "pdf",
        "asSingleFile": true,
	"references": [
		"Hahnweide EDST",
		"Speyer EDRY",
		"Koblenz-Winningen EDRK",
		"Aachen-Merzbrueck EDKA"
	]
    }
}
```
Diese Konfigurationsdatei würde z.B. alle 4 referenzierten Flugplätze in einer PDF-Datei ausgeben. Alternativ kann man  mit
`"asSingleFile": false,`
auch für jeden Flugplatz eine einzelne Datei generieren. Zur Vereinfachung der Listenerstellung, wird bei jeder Selektion eines Ordners in der Baumansicht der Text automatisch in die Zwischenablage kopiert, so dass man ihn in der Konfigurationsdatei nur noch einfügen muss. Diese Funktion sollte in der nächsten Version der SW verfügbar sein.

Diese Konfigurationsdatei ist natürlich nur provisorisch und soll in der Zukunft durch ein entsprechenden GUI ersetzt werden.

**Comment by Michael-Wellner** [comment]
Sehr geehrter Herr Paus,
damit haben Sie quasi tatsächlich bereits die komplette Exportfunktion implementiert, und was das angeht keine Wünsche mehr offen gelassen. :-)
Herzliche Grüße,
Michael Wellner

**Comment by RobeKrau** [comment]
Auf den GUI zur Erzeugung der Konfigurationsdatei freue ich mich schon!
